frappe/frappe-ui

- src/components/LoadingText.vue
> fix: loading indicator size in loading text component

- src/directives/onOutsideClick.js
- remove click handler instead of adding it
- use Map instead of an array to prevent dupes
> fix: remove clickHandler on unmounted

- src/resources/listResource.js
> feat: list resource: `hasPreviousPage` & `previous`

- src/components/Input.vue
index.js -> DatePicker -> Input -> index.js (debounce.js)
> fix: circular dependency

- src/components/FileUploader.vue
- src/index.js
- src/utils/fileUploadHandler.ts
Move file upload handler class to a separate file so that it can be used directly in the script.
> refactor: Separate file upload handler

- src/components/Autocomplete.vue
| Before | After |
| ------ | ----- |
| <img width="434" alt="image" src="https://github.com/frappe/frappe-ui/assets/30859809/a5726d2d-1fbd-426c-9948-5384f0107aa7"> | <img width="441" alt="image" src="https://github.com/frappe/frappe-ui/assets/30859809/30ae14f5-4c14-40bb-ae17-a8c80f339217"> |
> fix: added autocomplete prefix slot and changed prefix to item-prefix

- src/style.css
> fix: changed select chevron down icon

- src/components/TextInput.vue
1. Allow number type value
2. expose input ref
> fix: allow number type value to support text input type number

- src/components/CommandPalette/CommandPalette.vue
- src/components/CommandPalette/CommandPaletteItem.vue
- src/index.js
```vue
<template>
<CommandPalette
v-model:show="commandPalette.isOpen"
:search-query="commandPalette.searchQuery"
:groups="commandPalette.commands"
@select="commandPalette.select"
/>
</template>
<script setup>
import useCommandPalette from '@/useCommandPalette'
const commandPalette = useCommandPalette()
</script>
```
```js
// useCommandPalette.js
const commandPalette = reactive({
isOpen: false,
commands: [],
searchQuery: '',
open,
close,
search,
select(command) {
command.action()
close()
}
})
```
> feat: command palette

- src/components/ListView/ListRow.vue
- src/components/ListView/ListRowItem.vue
- src/components/ListView/ListView.vue
- src/index.js
```
<List
:columns="[
{ label: 'Title', value: 'title', class: 'flex-[2]' },
{ label: 'Status', value: 'status', class: 'flex-1' },
{ label: 'Chart Type', value: 'chart_type', class: 'flex-1' },
{ label: 'Data Source', value: 'data_source', class: 'flex-1' },
{ label: 'ID', value: 'name', class: 'flex-1' },
{ label: 'Created', value: 'created_from_now', class: 'flex-1 text-right' },
]"
:rows="queries.list"
>
<template #list-row="{ row: query }">
<ListRow as="router-link" :row="query" :to="{ name: 'Query', params: { name: query.name } }">
<ListRowItem class="flex-[2]"> {{ query.title }} </ListRowItem>
<ListRowItem class="flex-1"> {{ query.status }} </ListRowItem>
<ListRowItem class="flex-1"> {{ query.chart_type }} </ListRowItem>
<ListRowItem class="flex-1"> {{ query.data_source }} …
```
> feat: list component

- package.json
- src/components/Tabs.story.vue
- src/components/Tabs.vue
- src/index.js
```
<Tabs
v-model="tabIndex"
v-slot="{ tab }"
:tabs="[
{ label: 'Tab 1', content: 'Content of tab 1'},
{ label: 'Tab 2', content: 'Content of tab 2' }
]"
>
<div class="p-5">{{ tab.content }}</div>
</Tabs>
```
**Default:**
By setting `tabIndex` you can set the default tab selected
**Change Tab:**
By changing the same `tabIndex` you can also change the tab
https://github.com/frappe/frappe-ui/assets/30859809/99620315-d50d-43c6-a738-2b1df18d2c39
**Tab with Icon:**
Here icon is a component.
```
const tabs = [
{
label: 'Activity',
icon: ActivityIcon
},
{
label: 'Emails',
icon: EmailIcon
},
{
label: 'Calls',
icon: CallIcon
}
]
```
**Need a custom tab button UI use tab slot**
```
<Tabs>
<template #tab="{ tab, selected }">
// custom tab button
</template>
</Tabs>
```
**FrappeUI Storybook**
> feat: Tabs component

- src/components/ListView.story.md
- src/components/ListView.story.vue
- src/components/ListView/ListRow.vue
- src/components/ListView/ListRows.vue
- src/components/ListView/ListSelectBanner.vue
> fix: ListView Fix & Story/Docs update

- readme.md
Fixes the sample code in the README.
https://github.com/frappe/frappe-ui/blob/958942a270a4f4ea16c1fee6f68d89561bc6726e/readme.md?plain=1#L56-L60
https://github.com/frappe/frappe-ui/blob/3f041558b9627cebfe04c9463733775787b4097b/readme.md?plain=1#L55-L62
> docs: readme: correct sample code

- src/components/Autocomplete.story.vue
- src/components/Autocomplete.vue
> feat: multiple options in `Autocomplete` component

- src/components/ListView/ListHeaderItem.vue
- src/components/ListView/ListRow.vue
> style: removed absolute black color from text

- src/components/ListView.story.md
- src/components/ListView.story.vue
- src/components/ListView/ListHeader.vue
- src/components/ListView/ListHeaderItem.vue
- src/components/ListView/ListView.vue
Allow resizing column width just by dragging
> feat: Resize column

- src/components/ListView/ListHeader.vue
- src/components/ListView/ListHeaderItem.vue
1. Added debounce when the column is resized
2. Let ListHeader Component know that column is resized
> fix: Debounce & pass column width updated event to ListHeader Component

- src/components/ListView.story.md
- src/components/ListView.story.vue
- src/components/ListView/ListGroupHeader.vue
- src/components/ListView/ListGroupRows.vue
- src/components/ListView/ListGroups.vue
- src/components/ListView/ListView.vue
- src/icons/DownSolid.vue
> feat: Grouping in ListView

- vite.js
- required by https://github.com/frappe/builder/blob/95493c56ce9e98cadca45c226c3efb51e781c36e/frontend/vite.config.js#L34
cc @surajshetty3416
> feat: add pages to vite plugin for builder

- docs/resources/Resource.story.md
> Make use of declared variable

- docs/resources/Resource.story.md
> fix: mention default request method

- src/components/Breadcrumbs.vue
Added suffix slot for breadcrumbs
> feat: suffix slot for breadcrumbs

- src/resources/listResource.js
related 19989778f07cec427ece178afdb71973103b4fb2
> fix(ListDocResource): don't stringify args for run_doc_method

- src/components/Calendar.story.md
- src/components/Calendar/CalendarEvent.vue
Update calendar docs to improve grammar and language
> chore: calendar story docs cleanup

- src/components/Calendar.story.md
- src/components/Calendar/Calendar.vue
- src/components/Calendar/CalendarDaily.vue
- src/components/Calendar/CalendarMonthly.vue
- src/components/Calendar/CalendarWeekly.vue
- src/components/Calendar/calendarUtils.js
- src/components/Calendar/composables/useCalendarData.js
- src/components/Calendar/composables/useEventModal.js
- src/components/DateRangePicker.vue
- src/components/FileUploader.vue
- src/components/ListView/ListRow.vue
- src/components/Popover.vue
fix formatting for calendar component
> fix(formatting): run prettier on the calendar component

- src/components/CircularProgressBar.story.md
Format story of the Ring Progress Bar component
> chore: format progress ring story

- src/components/Textarea.story.vue
- src/components/Textarea.vue
> chore: added story for Textarea

- src/components/Textarea.story.vue
- src/components/Textarea.vue
chore: format text area component, with prettier
> fix(formatting): format text area component

- src/components/CircularProgressBar.vue
Before: 
After: also you can control the color of check by setting `text-green-500`
> fix: use check icon instead of check bg image

- src/components/FormControl.vue
Closes #148 
Add Required Attribute to Form Control
- Code
- Output
> feat: add required attribute in form control

- src/components/Dropdown.vue
1. Changed to composition API
2. Typescript support
> refactor: dropdown component

- src/components/Alert.vue
- src/components/Button.vue
- src/components/DatePicker.vue
- src/components/DateRangePicker.vue
- src/components/DateTimePicker.vue
- src/components/Dialog.vue
- src/components/types/Button.ts
- src/components/types/DatePicker.ts
- src/components/types/TextInput.ts
- src/utils/dates.ts
- src/utils/useDatePicker.ts
Rewrote components  - Options API -> composition API
Added typescript definitions
> refactor: rewrite Alert, Dialog, Date components in Composition API + add Typescript definitions

- package.json
- scripts/generateInterface.js
- vite.js
- yarn.lock
Automatically generates interfaces for doctypes defined in `frappeui.json`
This is how a sample `frappeui.json` might look like:
```jsonc
// frontend/frappeui.json
{
"typeGeneration": {
"output": "src/types/doctypes.ts", // this is also the default value if you dont specify output path
"input": {
"gameplan": [ // name of the app
"gp_project", // slugified name of the doctype so that it can find the .json file
"gp_member",
"gp_team",
"gp_comment",
"gp_discussion",
"gp_page",
"gp_task",
"gp_poll",
"gp_guest_access",
"gp_invitation",
"gp_user_profile",
"gp_notification"
]
}
}
}
```
Generated output:
```ts
interface DocType {
name: string
creation: string
modified: string
owner: string
modified_by: string
}
interface ChildDocType extends DocType {
parent?: string
parentfield?: string …
```
> feat: automatically generate typescript interfaces for doctypes

- src/tailwind/plugin.js
Changed line-height from 1.15 -> 1.4 for (2xs to xl), 1.3 for 2xl & 1.25 for 3xl
| Size | Before | After |
|-----|--------|------|
| 2xs |<img width="259" alt="image" src="https://github.com/user-attachments/assets/0f1726e9-aadc-4662-957a-1964458c67eb" />|<img width="259" alt="image" src="https://github.com/user-attachments/assets/c22c2eff-62fd-44f9-9e1b-14578825128d" />|
| xs |<img width="259" alt="image" src="https://github.com/user-attachments/assets/432be7e9-c523-4b99-abb9-637bd27c0bbb" />|<img width="259" alt="image" src="https://github.com/user-attachments/assets/97664e3f-1608-4bae-be94-48bca20a570c" />|
|  sm |<img width="259" alt="image" src="https://github.com/user-attachments/assets/49078f73-b060-4188-bda5-377aeca92b99" />|<img width="259" alt="image" …
> fix: 1.15 lineheight is too small

- src/components/Calendar/CalendarMonthly.vue
- src/components/Calendar/EventModalContent.vue
> fix: text and bg colors for calendar

- package.json
- src/tailwind/plugin.js
- vite.js
- yarn.lock
> fix: update heading and list styles in prose

- frappe/Billing/SignupBanner.vue
- frappe/Billing/TrialBanner.vue
- frappe/Help/HelpModal.vue
- frappe/Onboarding/GettingStartedBanner.vue
- frappe/Onboarding/IntermediateStepModal.vue
- frappe/Onboarding/OnboardingSteps.vue
- frappe/Onboarding/onboarding.js
- frappe/index.js
fixes: https://github.com/frappe/crm/issues/678
> fix: Onboarding fixes

- src/fonts/Inter/inter.css
> fix: exclude arabic font from InterVar & Inter

- src/components/Calendar.story.md
- src/components/Calendar.story.vue
- src/components/Calendar/Calendar.vue
- src/components/Calendar/CalendarDaily.vue
- src/components/Calendar/CalendarEvent.vue
- src/components/Calendar/CalendarMonthly.vue
- src/components/Calendar/CalendarTimeMarker.vue
- src/components/Calendar/CalendarWeekly.vue
- src/components/Calendar/EventModalContent.vue
- src/components/Calendar/ShowMoreCalendarEvent.vue
- src/components/Calendar/calendarUtils.js
Before:
<kbd>
</kbd>
After:
<kbd>
</kbd>
> fix: dark mode compatible & some minor fixes

- frappe/Onboarding/IntermediateStepModal.vue
IntermediateModal video should be autoplayed when it is mounted.
> fix: autoplay intermediate modal video

- package.json
Update the version in `package.json` from
0.1.149 to 0.1.150
> chore: update version in package.json

- src/components/Switch/Switch.vue
Before:
<kbd><img width="452" alt="Screenshot 2025-06-25 at 5 13 33 PM" src="https://github.com/user-attachments/assets/a07ded06-b08b-4d57-bb41-ecc36a57bd30" /></kbd>
After:
<kbd><img width="452" alt="Screenshot 2025-06-25 at 5 12 39 PM" src="https://github.com/user-attachments/assets/caa9cd9a-a521-446c-8aca-618bcc323b14" /></kbd>
> fix: ltr tailwind class is not needed

- src/components/Autocomplete/Autocomplete.story.vue
- src/components/Autocomplete/Autocomplete.vue
- src/components/Autocomplete/types.ts
As per discussion on https://github.com/frappe/frappe-ui/pull/265, I've added the default function for comparison.
@netchampfaris please check now.
Fixes: #263
> feat: Adding default function for autocomplete option comparison

- src/components/DatePicker/DatePicker.vue
Show formatted date if the formatter is passed as a prop
> fix: show formatted date

- src/components/ListView/ListEmptyState.vue
> fix(ListView): dark mode title and margin

- src/components/TextEditor/TextEditor.vue
- src/components/TextEditor/extensions/iframe/IframeNodeView.vue
- src/components/TextEditor/extensions/iframe/iframe-extension.ts
- src/components/TextEditor/extensions/iframe/utils.ts
- src/components/TextEditor/types.ts
Allows user to interact with the iframe. I need it for scrolling.
Also allows all same origin iframes.
> feat: interactive mode
