frappe/frappe-ui

src/components/TextEditor/TextEditor.vue

Removes this padding on the right

fix: text editor default right padding issue

---

src/components/Badge.vue

To make the badge extensible, the following changes have been made:
* Option to pass a color map object as prop to override the default map
* Separate out method to compute the color

refactor: Badge Component

---

.git-blame-ignore-revs
package.json
src/components/Alert.vue
src/components/Autocomplete.vue
src/components/Avatar.vue
src/components/Badge.vue
src/components/Button.vue
src/components/Card.vue
src/components/DatePicker.vue
src/components/Dialog.vue
src/components/Dropdown.vue
src/components/ErrorMessage.vue
src/components/Input.vue
src/components/Link.vue
src/components/LoadingText.vue
src/components/Modal.vue
src/components/Popover.vue
src/components/SuccessMessage.vue
src/components/TextEditor/InsertImage.vue
src/components/TextEditor/MentionList.vue
src/components/TextEditor/Menu.vue
src/components/TextEditor/TextEditor.vue
src/components/Toast.vue
src/components/Tooltip.vue
src/style.css
yarn.lock

Ref: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
Added official `prettier` plugin for TailwindCSS. Will give us consistent [recommended class ordering](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted).
Also, ran prettier on `src/*`.

chore: Add Tailwind CSS Prettier plugin

---

src/resources/documentResource.js

Example:
```typescript
whitelistedMethods:  {
lastCommunication: {
method: "last_communication",
onSuccess: (arg) => {},
},
}
````
Currently, `arg` is the parent doc, which we already have. It does make sense to return `data.message` instead, which is the return value of the white-listed method

fix(ux)!: white-listed method `onSuccess` argument must be `message`

---

src/components/Autocomplete.vue

1. Now if you open Autocomplete the search input will get focused
2. Added a slot for Autocomplete target
So now you can add custom UI

fix: slot for Autocomplete target

---

src/resources/listResource.js

Delete `_previousData` before stringifying
- Without this, object size used to grow exponentially on every update and if the original object is already big with JSON data in it, it use to cause heavy performance issues as it fills up memory in no time.
**Example with a small obj and with JSON string data:**
```JS
// original object
{
name: 'Frappe', 
data: '{"type":"company","location":"India"}'
}
// first update
{
"name": "Frappe 1",
"data": "{\"type\":\"company\",\"location\":\"India\"}",
"_previousData": "{\"name\":\"Frappe\",
\"data\":\"{\\\"type\\\":\\\"company\\\",\\\"location\\\":\\\"India\\\"}\"}"
}
// second update
{
"name": "Frappe 2",
"data": "{\"type\":\"company\",\"location\":\"India\"}",
"_previousData": "{\"name\":\"Frappe 1\",\"data\":\" …
```

perf: Delete `_previousData` before stringifying

---

src/components/Dialog.vue

As of now, this is always set to false and overrides the action.loading even if it exists (...action). Only happens when `actions` are passed as `options`.
Works fine for slot actions.

fix: default loading state for dialog actions

---

src/components/ListView/ListHeader.vue
src/components/ListView/ListHeaderItem.vue
src/components/ListView/ListRow.vue
src/components/ListView/ListRowItem.vue
src/components/ListView/ListRows.vue
src/components/ListView/ListSelectBanner.vue
src/components/ListView/ListView.vue
src/components/ListView/utils.js

This is how a custom ListView will look

refactor: listview component and added some more options

---

src/utils/fileUploadHandler.ts

In `FileUploader`, `doctype` is ignored if `docname` is not present. This PR change the behaviour to consider `doctype`, `docname` and `fieldname` as separate, unrelated properties. Please let me know if there is a reason to couple `doctype` and `docname` together.

fix: file uploader: consider `doctype` & `docname` separately

---

src/components/Dialog.vue

Reverts 4048cca50ea9c4270a142623b4d4ad1882413b68
Loading state is automatically handled using `handleAction`
This PR also fixes `handleAction`

refactor: handle dialog action loading state automatically

---

src/components/Tabs.story.md
src/components/Tabs.vue

1. Remove start animation
Before:
https://github.com/frappe/frappe-ui/assets/30859809/6a274d0f-3bf0-4edb-95ca-c5595fad6e0e
After:
https://github.com/frappe/frappe-ui/assets/30859809/5596912e-0eeb-482f-b3f6-dc301253e3b7
3. Made `indicatorLeft` customizable to handle custom tab header with custom left padding
4. Added docs

fix: Remove start animation from tabs component

---

src/components/Tabs.vue

Apply transition after mount to avoid start animation if default tab is other than the first tab
Before:
https://github.com/frappe/frappe-ui/assets/30859809/45c86eaf-d909-40c7-8224-f4a24493b1e5
After:
https://github.com/frappe/frappe-ui/assets/30859809/fdd98ca1-a8b5-4163-b952-1e3858c706a9

fix: (Tabs Component) Apply transition after mount

---

src/components/Tabs.vue

fix: Tabs Component fixes

---

src/components/ListView.story.md
src/components/ListView/ListHeaderItem.vue
src/components/ListView/ListView.vue

fix: align right not making header item right & set resize column default value as false

---

src/components/ListView.story.vue
src/components/ListView/ListEmptyState.vue
src/components/ListView/ListRow.vue
src/components/ListView/ListRowItem.vue
src/components/ListView/ListRows.vue
src/components/ListView/ListView.vue
src/components/Popover.vue
src/index.js

```js
emptyState: {
title: 'No Query Created.',
description: 'Create a new query to get started.',
button: {
label: 'New Query',
variant: 'solid',
onClick: () => (),
},
},
```
Also configurable by `slots`
```vue
<ListView>
<ListHeader />
<ListRows />
<ListEmptyState>
<p>No pages to display.</p>
<Button label="New Page" variant="solid" @click="() => {}" />
</ListEmptyState>
</ListView>
```
This ensures that the row height does not change if a row item prefix (like `Avatar`, or `Indicator`) is added to the list row item. It can be modified using `options.rowHeight`
```jsx
{
label: 'Label',
key: 'label',
width: 1,
getLabel: ({ row }) => row.label,
prefix: ({ row }) => <IndicatorIcon />,
}
```

feat: `ListEmptyState` and configurable `ListRowItem` prefix

---

src/components/Avatar.vue

Added label as `alt` attribute for Avatar image. SEO engines check for alt tags in images.

fix: alt attribute for avatar image

---

src/components/TextEditor/InsertLink.vue

FormControl was not imported for InsertLink Dialog.

fix: form control import

---

src/components/TextEditor/mention.js

Previously only 5 names were shown when mentioning a user in a comment. This number is too small for a large user base. I am increasing it to 10.

fix: increase mention result display count to 10

---

src/components/Avatar.vue

If the image request fails, fallback to label instead of breaking silently.

fix: silently failing image requests

---

src/components/ListView/ListRow.vue

https://github.com/user-attachments/assets/76d2c1a5-e190-4721-99a1-1e5bf43bce79
https://github.com/user-attachments/assets/53d52157-7515-4403-a288-91a090ac83b0

fix(ListView): disable hover state when row isn't clickable

---

src/components/FileUploader.vue

Reverts commit https://github.com/frappe/frappe-ui/commit/54caea6b7090dbed2cb0a0333c21dc0e6d9db3a0.
Fixes mime type selection regression introduced by it.
`inputRef` is exposed to handle changing accepted mime types outside the component.

Fileuploader fixes

---

src/components/Dialog.vue

Added a prop (`disableOutsideClickToClose`) to handle outside click to close option.
This is useful to avoid accidental dialog close in the middle unsaved changes.

fix(dialog): Add a prop to handle outside click to close option

---

src/components/CircularProgressBar.story.md
src/components/CircularProgressBar.story.vue
src/components/CircularProgressBar.vue
src/index.js

Add a highly customisable circular progress bar.
**Animated:**
https://github.com/user-attachments/assets/087b0652-9c1b-4b51-95b0-7faac0850ca5
Story & docs has also been added

feat: circular progress bar

---

src/components/Tooltip/Tooltip.vue

Currently, the tooltip z-index is 10. Gets hidden by other layers having z-index. Popover has a z-index of 100: https://github.com/frappe/frappe-ui/blob/96ecd6adf3669bd231e59ee442ac9fb3711a840d/src/components/Popover.vue#L20
Bumping it up for Tooltip too
**After**

fix: increase Tooltip's z-index to avoid overlap

---

src/utils/frappeRequest.js
src/utils/request.js

thrown by fetch API (like Network Errors) and these can be handled in `onError` function

fix(request): handle errors derived from fetch API 

---

src/components/Toast.vue

when html string is used in the toast problem appears
in the toast.vue component the title and text are using text interpolation so instead of using text interpolation using v-html directive we can avoid the issue

fix(toast): render html correctly

---

.github/workflows/story-publish.yml
src/utils/espressoVariables.js
src/utils/tailwind.config.js

Added a new GH action that
1. Checks if a PR was merged 
2. Builds Histoire
3. Adds CNAME (ui.frappe.io) file to build
4. Moves built dist to `gh-pages` branch
espressoVariables changed to `module.exports`

ci: Move histoire pages from netlify to GH pages 

---

src/components/TabButtons.vue

got `[Vue warn]: Failed to resolve component: FeatherIcon` originating from TabButtons component.

fix(TabButtons): register FeatherIcon

---

src/components/TextEditor/InsertVideo.vue
src/components/TextEditor/video-extension.js

While the editor is in edit mode, the video controls are not shown in the editor.
The video controls should be shown in the edit mode.

fix: show video controls when the editor is in edit mode

---

package.json

Alternate solution to this: https://github.com/frappe/frappe-ui/pull/220
- All frappe apps are already at vue 3.3+
- frappe-ui's yarn.lock is also at 3.5.12 - https://github.com/frappe/frappe-ui/blob/050467de060e546bea6c9fdb6c89f0997713020a/yarn.lock#L4570
- Moved typescript from dev dependency to prod dependency because importing types and using it for prop definitions requires typescript as a dependency. Ref: [https://vuejs.org/guide/typescript/composition-api.html\#syntax-limitations](https://vuejs.org/guide/typescript/composition-api.html/#syntax-limitations)
This also works if Props is imported from an external source. This feature requires TypeScript to be a peer dependency of Vue.
```vue
<script setup lang="ts">
import type { Props } from './foo'
const props = defineProps<Props>() …
```

fix: move typescript from devDependencies to dependencies + enforce vue 3.3+ for peerDependencies

---

src/components/Dialog.story.vue
src/components/Dialog.vue

- earlier context object was passed, but mistakenly got changed into close function being passed directly
- fix types
```
<Dialog :actions="[
{
label: 'Submit',
onClick(close) {
close() // close dialog
}
}
]">
```
```
<Dialog :actions="[
{
label: 'Submit',
onClick({ close }) {
close() // close dialog
}
}
]">
```

fix: dialog action context object

---

src/tailwind/plugin.js

- It was not working because borderColor key was defined twice and the second one was overriding the first one
**Before:**
**After:**

fix: Semantic color for border

---

src/components/TextEditor/InsertImage.vue
src/components/TextEditor/InsertVideo.vue

Image and Video Controls are returning empty video and img element if no url/ src is present. E.g.
**Solution:**
Only add image and video to editor if url/ src is present in any of these 2 elements.

fix: video and image controls should not have empty url

---

docs/components/confirm-dialog.md
src/components/ConfirmDialog.vue
src/utils/confirmDialog.js

There was no way of identifying if user discarded the confirmation.
`onCancel` will now be called when user closes the confirmation dialog.

fix(ConfirmDialog): Add onCancel handler

---

src/components/Autocomplete.vue
src/components/Rating/Rating.vue

1. Add `label` prop similar to `FormControl`
2. Add `loading` prop to display loading indicator
3. Add `show-footer` prop to show `clear` button even in case of `single` value
4. minor change in rating styles
- Before:
- After

feat: add `label`, `loading`, `placement` & `show-footer` props

---

src/components/Button/Button.vue

fix: button label overflow

---

src/components/FormControl.vue

FormControl did not have an explicit `modelValue` prop. The binding worked with individual controls because of fallthrough attributes mapped via `controlAttrs`. But when you check the component definition, there is no explicit modelValue prop in the definition, so Studio cannot render it in props editor
Explicitly added and mapped modelValue prop using defineModel
Also, removed unused labelClasses computed property

refactor(FormControl): explicitly add modelValue prop using defineModel

---

src/components/FormControl.vue
src/components/Input.vue
src/components/ListView/ListView.vue
src/components/TextEditor/TextEditor.vue

Studio applies raw styles to components via the style panel. But some compnents did not have style binding to the actual divs. Fix style propogation for such components:
- ListView
- FormControl
- Input
- TextEditor

fix: style propogation through components with `inheritAttrs: false`

---

src/components/FormControl/FormControl.vue
src/components/FormControl/types.ts

This was already mapped internally via `controlAttrs`, but making it explicit for a transparent component definition
For the same reason as: https://github.com/frappe/frappe-ui/pull/305
Note: Autocomplete & Checkbox don't have variants

fix(FormControl): add explicit variant prop

---

src/components/TextEditor/TextEditor.vue

**Issue:**
When we upload an Image or Video in TextEditor, we receive the following error:
This is because TextEditor requires a prop called `uploadFunction`, which by default is null. So we get this error.
**Fix:**
Add default functionality to `uploadFunction` prop, which uploads the file and adds `src` to the ImageNode.

fix: default function to upload files in TextEditor

---

src/components/FormControl/FormControl.vue
src/components/Select/types.ts
src/components/TextInput/types.ts

Reverting #305 since it does not handle `value` prop along with `modelValue`
If value is passed it gets ignore which is causing the issue in some existing components like DatePicker's input field

revert: explicitly add modelValue prop using defineMode #305

---

src/components/Charts/ECharts.vue

**Issue:**
The trend chart overflows on mobile because it has a minimum width of 400px
**Solution:**
Making it 300 px for mobile and 400 px for medium screen and above solves the chart overflow

fix(styles): echart width on mobile

---

src/components/TextEditor/video-extension.ts

Previously you can upload a video to the text editor but cant play it while editing this PR fixes that
Before 
https://github.com/user-attachments/assets/9cc8e0cc-eede-4ea9-9912-ba35113c2285
After
https://github.com/user-attachments/assets/bf70f556-be5f-4ed2-aebd-51c383c635a4

fix(TextEditor): allow video controls to be used while editing

---

frappe/Billing/TrialBanner.vue

Trial banner is not visible with the condition
`showBanner.value = data.setup_complete && data.plan.is_trial_plan && trialEndDays.value > 0`
The reason is that `setup_complete` is only completed when the user completes the framework's onboarding. But new apps redirect the users directly to the app, not the framework, so the framework setup wizard will not be complete and TrialBanner will not be displayed.

fix: show trial banner regardless of setup completed or not

---

src/components/TextEditor/TextEditor.vue
src/components/TextEditor/extensions/content-paste-extension.ts
src/components/TextEditor/extensions/image/image-extension.ts
src/components/TextEditor/extensions/markdown-paste-extension.ts
src/utils/fileUploadHandler.ts

**Issue:**
When we paste images via clipboard into the text editor we get the following result:
**Reason:**
We only handle Text pasting from clipboard
ref:
**Fix:**
Find images from clipboard and use `processMultipleImages` function to upload images via clipboard
1. Image drop works like before
2. Image pasting via clipboard also works
https://github.com/user-attachments/assets/8d583d01-f095-4b86-8ac0-9060b48bc685

fix: image pasting via clipboard

---

src/components/TabButtons/TabButtons.vue

The missing import was breaking the UI

fix: import Button in TabButtons

---

src/components/Tree/Tree.vue
src/components/Tree/types.ts

Allow passing the initial collapsed state for all nodes in the Tree component.

feat: add default collapsed prop for tree component

---

src/utils/useFileUpload.ts

Allows using the `useFileUpload` utility for upload functions that aren't as tightly coupled with the framework.

feat: allow dynamic params to useFileUpload

---

components.d.ts
src/components/Dropdown/Dropdown.story.vue
src/components/Dropdown/Dropdown.vue
src/components/Dropdown/types.ts
src/components/Switch/Switch.story.vue
src/components/Switch/Switch.vue
src/components/Switch/types.ts

Makes switch a first class component of Dropdown.
This allows users to, for example, keep the dropdown open after clicking:
https://github.com/user-attachments/assets/75b420ae-2ad4-45ef-a0cd-e7abd6611504

feat: add switch to dropdown
